happy-travel/osaka

HappyTravel.PredictionService/Infrastructure/Extensions/ElasticSearchServiceCollectionExtensions.cs
HappyTravel.PredictionService/Models/Elasticsearch/Location.cs
HappyTravel.PredictionService/Models/Location.cs
HappyTravel.PredictionService/Models/MapperLocationTypes.cs
HappyTravel.PredictionService/Services/HttpClients/IStaticDataMapperHttpClient.cs
HappyTravel.PredictionService/Services/HttpClients/StaticDataMapperHttpClient.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs
HappyTravel.PredictionService/Services/Locations/LocationsService.cs
HappyTravel.PredictionService/Startup.cs
HappyTravel.PredictionService/appsettings.Development.json
HappyTravel.PredictionService/appsettings.Local.json

Optimize search query

---

HappyTravel.PredictionService/Infrastructure/Extensions/AuthenticationCollectionExtensions.cs
HappyTravel.PredictionService/appsettings.Development.json

Fix appsettings.json

---

HappyTravel.PredictionService/HappyTravel.PredictionService.csproj
HappyTravel.PredictionService/Infrastructure/Extensions/ElasticSearchHealthCheck.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs
HappyTravel.PredictionService/Services/Locations/LocationsService.cs
HappyTravel.PredictionService/Startup.cs

Add ElasticSearch healthcheck

---

HappyTravel.PredictionService/Infrastructure/Extensions/HttpClientsCollectionExtension.cs
HappyTravel.PredictionService/Services/HttpClients/IMapperHttpClient.cs
HappyTravel.PredictionService/Services/HttpClients/MapperHttpClient.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs
HappyTravel.PredictionService/Startup.cs

Modify authorization in MapperHttpClient

Modify authorization in MapperHttpClient

---

HappyTravel.PredictionService/Services/HttpClients/MapperHttpClient.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

Decrease batch size of uploaded locations from the mapper

Decrease batch size of uploaded locations from the mapper

---

HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

Modify the batch size of uploaded locations

Modify the batch size of uploaded locations

---

HappyTravel.PredictionService/Controllers/LocationsController.cs
HappyTravel.PredictionService/Controllers/LocationsManagementController.cs

The Location re-upload endpoint runs a separate task to upload locations

The Location re-upload endpoint runs a separate task to upload locations

---

HappyTravel.PredictionService/Controllers/LocationsManagementController.cs
HappyTravel.PredictionService/Infrastructure/Logging/LogEvents.json
HappyTravel.PredictionService/Infrastructure/Logging/LoggerExtensions.g.cs
HappyTravel.PredictionService/Services/HttpClients/MapperHttpClient.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

Add logs to LocationsManagerService

Add logs to LocationsManagerService

---

HappyTravel.PredictionService/Controllers/LocationsController.cs
HappyTravel.PredictionService/Controllers/LocationsManagementController.cs
HappyTravel.PredictionService/Controllers/PredictionsController.cs
HappyTravel.PredictionService/Infrastructure/Extensions/ElasticSearchServiceCollectionExtensions.cs
HappyTravel.PredictionService/Infrastructure/HttpClientNames.cs
HappyTravel.PredictionService/Infrastructure/Logging/LogEvents.json
HappyTravel.PredictionService/Infrastructure/Logging/LoggerExtensions.g.cs
HappyTravel.PredictionService/Models/Elasticsearch/Location.cs
HappyTravel.PredictionService/Models/Elasticsearch/Suggestion.cs
HappyTravel.PredictionService/Models/Response/Prediction.cs
HappyTravel.PredictionService/Services/IPredictionsService.cs
HappyTravel.PredictionService/Services/Locations/ILocationsService.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs
HappyTravel.PredictionService/Services/Locations/LocationsService.cs
HappyTravel.PredictionService/Services/PredictionsService.cs

Improvements of the predictions searching:
- Sequential search by a prediction text: Country, Locality, Accommodation (exclude n-grams)
- Add weights for the suggester's input
- Add Image path to the prediction response
- Add some synonyms for testing

NIJO-1292. Improvements of the predictions searching

---

HappyTravel.PredictionService/Infrastructure/Extensions/ElasticSearchServiceCollectionExtensions.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

Recreate the index with a new mapping before uploading locations

Recreate the index with a new mapping before uploading locations

---

HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

Collect Nest client error

---

HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

Fix error logging

---

HappyTravel.PredictionService/Infrastructure/Extensions/ElasticSearchServiceCollectionExtensions.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

Increase NEST request timeout

---

HappyTravel.PredictionService/HappyTravel.PredictionService.csproj
HappyTravel.PredictionService/Infrastructure/Extensions/ElasticSearchServiceCollectionExtensions.cs
HappyTravel.PredictionService/Infrastructure/Extensions/ElasticSynonymsHelper.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

Add synonyms to the index from LocationsNameNormalizer

Add synonyms to the index from LocationsNameNormalizer

---

HappyTravel.PredictionService/Controllers/LocationsManagementController.cs
HappyTravel.PredictionService/HappyTravel.PredictionService.csproj
HappyTravel.PredictionService/Infrastructure/Extensions/HttpClientsCollectionExtension.cs
HappyTravel.PredictionService/Infrastructure/Logging/LogEvents.json
HappyTravel.PredictionService/Infrastructure/Logging/LoggerExtensions.g.cs
HappyTravel.PredictionService/Program.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

- Fix event_id in LogEvents
- Fix Sentry exception capturing
- Add retry PolicyHandler to the mapper's HttpClient

Fix event_id in log events, some minor fixes

---

HappyTravel.PredictionService/Infrastructure/Extensions/ElasticSearchServiceCollectionExtensions.cs
HappyTravel.PredictionService/Services/Locations/LocationsManagementService.cs

Increase prediction's input length and expand search variants for accommodations

Increase prediction's input length and expand search variants for accommodations

---

HappyTravel.Osaka.Api/HappyTravel.PredictionService.csproj

Hotfix. Removed old project from folder

Removed old project from folder

---

HappyTravel.Osaka.Api/Controllers/LocationsManagementController.cs
HappyTravel.Osaka.Api/HappyTravel.Osaka.Api.csproj
HappyTravel.Osaka.Api/Infrastructure/Extensions/ElasticSearchServiceCollectionExtensions.cs
HappyTravel.Osaka.Api/Infrastructure/Extensions/ElasticSynonymsHelper.cs
HappyTravel.Osaka.Api/Services/Locations/LocationsService.cs
HappyTravel.Osaka.Api/Startup.cs
README.md

- Adds improvements to the search service
- Updates nuget packages
- Updates readme.md

Adds improvements to the search service

---

HappyTravel.Osaka.Api/Models/Location.cs
HappyTravel.Osaka.Api/Models/Updates/Coordinate.cs

Fix the deserialization of location coordinates

Fix the deserialization of location coordinates

---

HappyTravel.Osaka.Api/Services/UpdateFromStreamWorker.cs

fix UpdateFromStreamWorker service

fix UpdateFromStreamWorker service

---

HappyTravel.Osaka.Api/Models/Updates/LocationEntry.cs
HappyTravel.Osaka.Api/Services/UpdateFromStreamWorker.cs

Fix property name

---

HappyTravel.Osaka.Api/Services/Locations/PredictionsManagementService.cs

Fix a prediction text a zone location

Fix a prediction text a zone location

---

HappyTravel.Osaka.Api/Services/Locations/PredictionsManagementService.cs
HappyTravel.Osaka.Api/Services/UpdateFromStreamWorker.cs

Improves error logging

---

HappyTravel.Osaka.Api/HappyTravel.Osaka.Api.csproj

Updated contracts to 1.8.3.1

---

HappyTravel.Osaka.Api/HappyTravel.Osaka.Api.csproj

Updated contracts to 2.0.0

---

HappyTravel.Osaka.Api/Infrastructure/Extensions/PredictionsUpdateExtensions.cs
HappyTravel.Osaka.Api/appsettings.Local.json

Add redis syncTimeout option

---

HappyTravel.Osaka.Api/HappyTravel.Osaka.Api.csproj

Automatic PR, generated by a script

Updated StdOutLogger to 1.4.0

---

HappyTravel.Osaka.Api/Services/Locations/LocationsService.cs

Fix The given key 'countrySuggester' was not present in the dictionary
https://github.com/happy-travel/agent-app-project/issues/486

Fix The given key 'countrySuggester' was not present in the dictionary

---

HappyTravel.Osaka.Api/HappyTravel.Osaka.Api.csproj

Automatic PR, generated by a script

Updated ErrorHandling to 1.2.2
